/**
 **************************************************
 * @file        Inkplate4TEMPERA_Image_Converter.ino
 * @brief       Example showing how to display an image on Inkplate 4TEMPERA
 *              using the Soldered Image Converter tool.
 *
 * @details     This example demonstrates how to use the Soldered Image
 *              Converter to prepare an image for display on Inkplate 4TEMPERA.
 *              The tool converts any image into a C byte array stored in
 *              a header file (.h) which can be directly included in your
 *              Arduino sketch.
 *
 *              Tool workflow:
 *              1. Open the Image Converter at https://tools.soldered.com/tools/image-converter/
 *              2. Upload your image and select "Inkplate 4TEMPERA" as the target board.
 *              3. Choose the display mode:
 *                 - 1-bit (Black & White) - fastest refresh, highest contrast
 *                 - 3-bit (Grayscale) - 8 shades of gray
 *              4. Adjust dithering, resize, and other options as needed.
 *              5. Save the generated header file (image.h) and place it
 *                 in the same folder as this sketch.
 *
 *              image_w and image_h are automatically defined in the generated
 *              image.h. For grayscale mode use INKPLATE_3BIT instead of
 *              INKPLATE_1BIT. display.clearDisplay() clears only the internal
 *              framebuffer, so display.display() must be called to push it to
 *              the screen. Expected output is your converted image displayed on
 *              the Inkplate 4TEMPERA e-paper screen.
 *
 * Requirements:
 * - Board:      Soldered Inkplate 4TEMPERA
 * - Hardware:   Inkplate 4TEMPERA, USB cable
 * - Extra:      The image header file (image.h) generated by the tool
 *
 * How to use:
 * 1) In Boards Manager -> Inkplate Boards, select "Soldered Inkplate4TEMPERA"
 *    from Tools -> Board.
 * 2) Generate image.h using the Image Converter at
 *    https://tools.soldered.com/tools/image-converter/
 * 3) Place image.h in the same folder as this sketch.
 * 4) Upload the sketch to Inkplate 4TEMPERA.
 * 5) The image appears on the display after initialization.
 *
 * @note        Quick start guide:
 *              https://docs.soldered.com/inkplate/4tempera/quick-start-guide/
 * @note        Want to learn more about Inkplate? Visit
 *              https://docs.soldered.com/inkplate/
 * @note        Looking to get support? Write on our community forum:
 *              https://community.soldered.com/
 * @note        Image converter tool:
 *              https://tools.soldered.com/tools/image-converter/
 *
 * @author      Soldered
 * @date        2026-04
 * @license     GNU GPL V3
 **************************************************/

// Next 3 lines are a precaution, you can ignore those, and the example would also work without them
#ifndef ARDUINO_INKPLATE4TEMPERA
#error "Wrong board selection for this example, please select Soldered Inkplate4TEMPERA in the boards menu."
#endif

#include "Inkplate.h" // Include the Inkplate library
#include "image.h"    // Include the image header generated by the Image Converter tool

Inkplate display(INKPLATE_1BIT); // 1-bit mode (black & white)
//Inkplate display(INKPLATE_3BIT); // Uncomment for 3-bit mode (grayscale, 8 shades)

void setup() {
    display.begin();        // Initialize the display hardware
    display.clearDisplay(); // Clear the frame buffer (does NOT clear the physical screen)

    display.image.draw(image, 0, 0, image_w, image_h); // Arguments are: array variable name, start X, start Y,  size X, size Y

    display.display(); // Refresh the e-paper display to show the image
}

void loop() {
    // No code needed here for this example
}
