/**
 **************************************************
 * @file        Inkplate6PLUS_Custom_Diacritics.ino
 * @brief       HOW-TO: add custom Unicode glyphs (German ä ö ü ß Ä Ö Ü here)
 *              to a GFX font, for Soldered Inkplate 6PLUS, using the Soldered
 *              Font Converter tool.
 *
 * @details     THE PROBLEM
 *              ------------
 *              The bundled GFX fonts (FreeSans/FreeSerif/FreeMono, see
 *              Fonts/) only cover 7-bit ASCII (0x20-0x7E). Adafruit_GFX's
 *              text renderer (Adafruit_GFX::write()/drawChar(), which
 *              Inkplate's print()/write() calls into) looks up glyphs with a
 *              single BYTE index: glyphTable[code - font->first]. There is
 *              no Unicode decoding anywhere in that path.
 *
 *              So a character above 0xFF can NEVER be printed via
 *              print()/write(), no matter what a .ttf file contains -
 *              rebuilding a font from a TTF that "has" ä/ö/ü doesn't help by
 *              itself. Worse, typing ä/ö/ü/ß directly into a string literal
 *              in the .ino doesn't work either: the Arduino source file is
 *              UTF-8, so e.g. 'ä' (U+00E4) is stored as the TWO bytes 0xC3
 *              0xA4, and print() would look up (and draw) two wrong glyphs
 *              at codes 0xC3 and 0xA4 instead of the one you wanted.
 *
 *              THE FIX - THE FONT CONVERTER TOOL
 *              --------------------------------------
 *              The Soldered Font Converter builds a complete GFXfont header
 *              (7-bit ASCII + whatever extra characters you name) straight
 *              from a .ttf, right in the browser - no install, no compiler.
 *
 *              Tool workflow:
 *              1. Open the Font Converter at https://tools.soldered.com/tools/font-converter/
 *              2. Upload a .ttf that contains the characters you need (GNU
 *                 FreeFont has broad Unicode coverage, including Latin-1
 *                 Supplement where ä/ö/ü/ß/Ä/Ö/Ü live, and is a good first
 *                 place to look: https://savannah.gnu.org/projects/freefont/)
 *              3. Set the size in pt and a header/font name (e.g.
 *                 FreeSansGerman18pt7b).
 *              4. In "Extra characters", type the non-ASCII characters to
 *                 add (here: ä ö ü ß Ä Ö Ü).
 *              5. Enter sample text to preview, then click Convert.
 *              6. Download the generated header file (FreeSansGerman18pt7b.h)
 *                 and place it in the same folder as this sketch.
 *
 *              That's how FreeSansGerman18pt7b.h in this folder was
 *              generated. The tool assigns each extra character a byte code
 *              right after the last ASCII one (0x7E), counting up with zero
 *              gaps - here that's 0x7F through 0x85 - and shows the exact
 *              CH_* #defines below (and an example sketch using them) so you
 *              can copy them straight in. For a different language, swap the
 *              character list (and the .ttf if you want a different source
 *              font); nothing else changes.
 *
 *              In the sketch, print the extra characters via their assigned
 *              byte codes - either display.write((uint8_t)0x7F), or (used
 *              below, reads better inside a sentence) adjacent
 *              string-literal concatenation: CH_ae "chzt" expands to
 *              "\x7f" "chzt", i.e. one raw byte 0x7F followed by the literal
 *              text "chzt". Never type the accented character itself into
 *              the string - see "THE PROBLEM" above for why.
 *
 * Requirements:
 * - Board:      Soldered Inkplate 6PLUS
 * - Hardware:   Inkplate 6PLUS, USB cable
 * - Extra:      The font header file (FreeSansGerman18pt7b.h) generated by
 *               the tool
 *
 * How to use:
 * 1) Generate FreeSansGerman18pt7b.h using the Font Converter at
 *    https://tools.soldered.com/tools/font-converter/
 * 2) Place FreeSansGerman18pt7b.h in the same folder as this sketch.
 * 3) In Boards Manager -> Inkplate Boards, select "Soldered Inkplate 6PLUS"
 *    from Tools -> Board.
 * 4) Upload the sketch to Inkplate 6PLUS.
 * 5) The German sentence and the full extra-glyph legend appear on screen.
 *
 * @note        Quick start guide: Inkplate 6PLUS has no dedicated page yet, see
 *              https://docs.soldered.com/inkplate/
 * @note        Want to learn more about Inkplate? Visit
 *              https://docs.soldered.com/inkplate/
 * @note        Looking to get support? Write on our community forum:
 *              https://community.soldered.com/
 * @note        Font converter tool:
 *              https://tools.soldered.com/tools/font-converter/
 *
 * @author      Soldered Electronics
 * @date        2026-08-27
 **************************************************/

#if !defined(ARDUINO_INKPLATE6PLUS) && !defined(ARDUINO_INKPLATE6PLUSV2)
#error "Wrong board selection for this example, please select e-radionica Inkplate 6Plus or Soldered Inkplate 6Plus in the boards menu."
#endif

#include "Inkplate.h"
#include "FreeSansGerman18pt7b.h" // FreeSans18pt7b + ä ö ü ß Ä Ö Ü at 0x7F-0x85

// Byte codes the extra glyphs were placed at inside FreeSansGerman18pt7b.h
// (shown by the Font Converter tool when the font was generated - see header
// comment above). Used as adjacent string literals, e.g. CH_AE "rger" -> "\x83" "rger".
#define CH_ae "\x7f" // ä  U+00E4
#define CH_oe "\x80" // ö  U+00F6
#define CH_ue "\x81" // ü  U+00FC
#define CH_sz "\x82" // ß  U+00DF
#define CH_AE "\x83" // Ä  U+00C4
#define CH_OE "\x84" // Ö  U+00D6
#define CH_UE "\x85" // Ü  U+00DC

Inkplate display(INKPLATE_1BIT);

void setup()
{
    display.begin();
    display.clearDisplay();
    display.setTextColor(BLACK);
    display.setFont(&FreeSansGerman18pt7b);

    // A German sentence exercising every extra glyph: Ö, ä, ü (x2), ö, ß, Ü, Ä.
    display.setCursor(10, 60);
    display.print(F(CH_OE "sterreichische M" CH_ae "dchen " CH_ue "ben ihre Gr" CH_oe CH_sz "e."));
    display.setCursor(10, 100);
    display.print(F(CH_UE "ber " CH_AE "rger spricht niemand gern."));

    // Full legend of every extra glyph, upper- then lower-case.
    display.setCursor(10, 150);
    display.print(F(CH_AE CH_OE CH_UE " " CH_ae CH_oe CH_ue CH_sz));

    display.display();
}

void loop()
{
}
