name: Run clang-format Linter

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: "./src"
          exclude: "./src/libs"
          extensions: "h,cpp,c,ino"
          clangFormatVersion: 12
          inplace: True
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "Committing clang-format changes"
